name: Test Action Workflow

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Test Action
        uses: GatlingX/hackbot-ci@v0.1.2
        with:
          address: <your-address>
          port: <your-port>
          api_key: ${{ secrets.YOUR_KEY }}
          output: "results.json"
          artifact: true
          generate_issues: true
          issues_repo: "username/repo"
        id: test-action

